name: Build and Deploy to EKS
###
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_ACCOUNT_ID: "361769567498"
  AWS_REGION: "us-east-2"
  IMAGE_REPO_NAME: "january-class"
  CLUSTER_NAME: "app-eks-cluster"

jobs:
  build-push-deploy:
    name: Build → Push to ECR → Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::361769567498:role/GitHubActionsTerraformRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Set build version
        id: vars
        run: echo "VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_REPO_NAME:$VERSION .
          docker tag $IMAGE_REPO_NAME:$VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$VERSION

      - name: Push image to ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$VERSION

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy To EKS via Helm
        run: |
           helm upgrade --install web-app ./web-app --namespace config --set image.tag="$VERSION" -f ./web-app/values.yaml
